### ISSUE TITLE
Rainbow effect too fast

### ISSUE THREAD

**Issue by dschiedsch** [CommanderRedYT/ws2812-clock#2]
The rainbow animation is way too fast for a comfortable feeling
Please introduce a speed variable to set the animation speed

**Comment by CommanderRedYT** [comment]
This is already implemented by the animation Multiplier config variable

**Comment by dschiedsch** [comment]
The multiplier doesn't make the animation slower but increases the pause between animation steps
which makes the animation very choppy
the animation should still run smooth but the change per animation cycle should be less

**Comment by CommanderRedYT** [comment]
Did you try it with the website closed? As of now, there are still some lags from the webserver
