### ISSUE TITLE
Enhancement mqtt discovery

### ISSUE THREAD

**Issue by dschiedsch** [CommanderRedYT/ws2812-clock#3]
Add a mqtt autodiscovery feature so that HomeAssistant can deiscover the device automatically
https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery

**Comment by CommanderRedYT** [comment]
What should it be discovered as?
Should there also be write-able stats?

**Comment by dschiedsch** [comment]
three sensors (temp, humidity, pressure)
maybe make the update rate a write-able stat
or at least configurabel via the web interface

here is an example of a mqtt config from a temp sensor I use

`{"name":"Home Buttons 83653D Temperature","uniq_id":"HBTNS-2308-032-83653D_temperature","stat_t":"homebuttons/Home Buttons 83653D/temperature","dev_cla":"temperature","unit_of_meas":"°C","exp_aft":660,"dev":{"ids":["HBTNS-2308-032-83653D"]}}`

and here of a humidity sensor:

`{"name":"Home Buttons 83653D Humidity","uniq_id":"HBTNS-2308-032-83653D_humidity","stat_t":"homebuttons/Home Buttons 83653D/humidity","dev_cla":"humidity","unit_of_meas":"%","exp_aft":660,"dev":{"ids":["HBTNS-2308-032-83653D"]}}`

**Comment by dschiedsch** [comment]
also I would like the mqtt update rate to be either settable or at least slower than the 1sec it is now, otherwise it will just spam the mqtt channel
