### ISSUE TITLE
home assistant brightness control not working completely

### ISSUE THREAD

**Issue by dschiedsch** [CommanderRedYT/ws2812-clock#7]
I can control brightness from ha, however if i switch off and on it returns to some default brightness and not the brightness i set before
also ha doesn't display the current brightness at all

**Comment by CommanderRedYT** [comment]
I am not entirely sure why it doesn't display the brightness, but I can try debugging it. The whole brightness thing was hours of figuring things out. Do you maybe have a working brightness slider config you could share? Then I could just replicate that

**Comment by dschiedsch** [comment]
here is the topic from another light:
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state"
    }
  ],
  "brightness": true,
  "brightness_scale": 254,
  "command_topic": "zigbee2mqtt/Schlafzimmer/set",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x000d6f0016bcd3e9"
    ],
    "manufacturer": "OSRAM",
    "model": "Zigbee 3.0 DALI CONV LI dimmer for DALI-based luminaires (only one device) (4062172044776_1)",
    "name": "Schlafzimmer",
    "sw_version": "1.0.0.8-6.5.5.b"
  },
  "effect": true,
  "effect_list": [
    "blink",
    "breathe",
    "okay",
    "channel_change",
    "finish_effect",
    "stop_effect"
  ],
  "json_attributes_topic": "zigbee2mqtt/Schlafzimmer",
  "name": "Schlafzimmer",
  "schema": "json",
  "state_topic": "zigbee2mqtt/Schlafzimmer",
  "unique_id": "0x000d6f0016bcd3e9_light_zigbee2mqtt"
}
